name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Provision EC2 instance'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./aws/ec2

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new Terraform working directory, verify the format, and execute the plan
    - name: Terraform Init
      run: |
        terraform init
        terraform fmt -check
        terraform plan

    # Abort if the plan failed
    - name: Check for Terraform failure
      if: steps.plan.outcome == 'failure'
      run: exit 1
      
    # Apply the plan to the environment
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve
        terraform output > terraform.env
        cat terraform.env



# ----
